Update Category with PATCH --------------------------
	PATCH method is used to partially update a resource

	* Controller

		@RestController
		@RequestMapping(URI)
		public class CategoryController {

			public static final String URI = "/api/v1/categories";

			private final CategoryRepository categoryRepository;

			public CategoryController(CategoryRepository categoryRepository) {
				this.categoryRepository = categoryRepository;
			}

			...

			@PatchMapping("/{id}")
			public Mono<Category> patch(@PathVariable String id, @RequestBody Category category) {
				Category categoryToPatch = categoryRepository.findById(id).block();
				if (categoryToPatch == null) {
					throw new ResourceNotFoundException();
				}

				if (StringUtils.hasText(category.getName()) && !category.getName().equals(categoryToPatch.getName())) {
					categoryToPatch.setName(category.getName());
					categoryRepository.save(categoryToPatch);
				}

				return Mono.just(categoryToPatch);
			}
		}

	* Test

		@ExtendWith(MockitoExtension.class)
		class CategoryControllerTest {

			private WebTestClient webTestClient;

			@Mock
			private CategoryRepository mockCategoryRepository;

			@InjectMocks
			private CategoryController categoryController;

			@BeforeEach
			void setUp() {
				webTestClient = WebTestClient.bindToController(categoryController).build();
			}

			...

			@Test
			void patch() {
				//given
				when(mockCategoryRepository.save(any(Category.class))).thenReturn(Mono.just(Category.builder().build()));
				Mono<Category> categoryToPatchMono = Mono.just(Category.builder().name("Cat1").build());

				// when
				webTestClient.patch().uri(CategoryController.URI + "/1")
						.body(categoryToPatchMono, Category.class)
						.exchange()
						.expectStatus()
						.isOk();

				// then
			}
		}

	* RESULT

		14:03:35.093 [parallel-1] ERROR org.springframework.web.server.adapter.HttpWebHandlerAdapter - [5e70f804] 500 Server Error for HTTP PATCH "/api/v1/categories/1"
		java.lang.NullPointerException: null
			at guru.springframework.spring5webfluxrest.controller.CategoryController.patch(CategoryController.java:53)
			Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
		Error has been observed at the following site(s):
			|_ checkpoint ⇢ HTTP PATCH "/api/v1/categories/1" [ExceptionHandlingWebHandler]
		Stack trace:
				at guru.springframework.spring5webfluxrest.controller.CategoryController.patch(CategoryController.java:53)
				...
		14:03:35.097 [parallel-1] DEBUG org.springframework.test.web.reactive.server.HttpHandlerConnector - Creating client response for  PATCH "/api/v1/categories/1"
		14:03:35.102 [parallel-1] DEBUG org.springframework.web.reactive.function.client.ExchangeFunctions - [10667848] [540cb054] Response 500 INTERNAL_SERVER_ERROR
		14:03:35.111 [main] ERROR org.springframework.test.web.reactive.server.ExchangeResult - Request details for assertion failure:

		> PATCH /api/v1/categories/1
		> WebTestClient-Request-Id: [1]
		> Content-Type: [application/json]
		> Content-Length: [25]

		{"id":null,"name":"Cat1"}

		< 500 INTERNAL_SERVER_ERROR Internal Server Error
		<

		0 bytes of content (unknown content-type).

		java.lang.AssertionError: Status expected:<200 OK> but was:<500 INTERNAL_SERVER_ERROR>
		Expected :200 OK
		Actual   :500 INTERNAL_SERVER_ERROR
		<Click to see difference>

		at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
		at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
		at org.springframework.test.web.reactive.server.StatusAssertions.lambda$assertStatusAndReturn$4(StatusAssertions.java:225)
		at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:227)
		at org.springframework.test.web.reactive.server.StatusAssertions.assertStatusAndReturn(StatusAssertions.java:225)
		at org.springframework.test.web.reactive.server.StatusAssertions.isOk(StatusAssertions.java:67)
		at guru.springframework.spring5webfluxrest.controller.CategoryControllerTest.patch(CategoryControllerTest.java:114)
		...

		ANSWER: In the Controller we perform a 'categoryRepository.findById(id).block()', but as we forgot to mock the 'categoryRepository.findById(id)' method call, it returns a null there, so we end up with a NPE on .block()