Create Category with POST -------------------------
	@RestController
	@RequestMapping(URI)
	public class CategoryController {

		public static final String URI = "/api/v1/categories";

		private final CategoryRepository categoryRepository;

		public CategoryController(CategoryRepository categoryRepository) {
			this.categoryRepository = categoryRepository;
		}

		...

		@PostMapping
		@ResponseStatus(HttpStatus.CREATED)                             // Make sure to return a 201 HTTP STATUS for object creations
		public Mono<Void> create(Publisher<Category> categoryStream) {  // called categoryStream as it can be a stream of one or more objects: Publisher is part of Reactive Streams API. Mono and Flux are implementations of a Publisher, so this method will be able to take in both.
			return categoryRepository.saveAll(categoryStream).then();   // .then() makes sure to return a Mono<Void>
		}
	}

	@ExtendWith(MockitoExtension.class)
	class CategoryControllerTest {

		private WebTestClient webTestClient;

		@Mock
		private CategoryRepository mockCategoryRepository;

		@InjectMocks
		private CategoryController categoryController;

		@BeforeEach
		void setUp() {
			webTestClient = WebTestClient.bindToController(categoryController).build();
		}

		...

		@Test
		void create() {
			// given
			Flux<Category> savedCategories = Flux.just(Category.builder().build());
			Mono<Category> categoryToSave = Mono.just(Category.builder().name("Cat1").build());
			when(mockCategoryRepository.saveAll(any(Publisher.class))).thenReturn(savedCategories);

			// when
			webTestClient.post().uri(CategoryController.URI)
					.body(categoryToSave, Category.class)
					.exchange()
					.expectStatus()
					.isCreated();

			// then
		}
	}

	RESULT ERROR:

		08:50:01.105 [parallel-1] ERROR org.springframework.web.server.adapter.HttpWebHandlerAdapter - [613cb219] 500 Server Error for HTTP POST "/api/v1/categories"
		java.lang.IllegalStateException: ModelAttributeMethodArgumentResolver does not support multi-value reactive type wrapper: org.reactivestreams.Publisher<guru.springframework.spring5webfluxrest.domain.Category>
			at org.springframework.util.Assert.state(Assert.java:97)
			Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
		Error has been observed at the following site(s):
			|_ checkpoint ⇢ HTTP POST "/api/v1/categories" [ExceptionHandlingWebHandler]
		Stack trace:
				at org.springframework.util.Assert.state(Assert.java:97)
				at org.springframework.web.reactive.result.method.annotation.ModelAttributeMethodArgumentResolver.resolveArgument(ModelAttributeMethodArgumentResolver.java:106)
				at org.springframework.web.reactive.result.method.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:118)
				at org.springframework.web.reactive.result.method.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:200)
				at org.springframework.web.reactive.result.method.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:137)
				at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.lambda$handle$1(RequestMappingHandlerAdapter.java:199)
				at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
				...
				at java.lang.Thread.run(Thread.java:748)
		08:50:01.109 [parallel-1] DEBUG org.springframework.test.web.reactive.server.HttpHandlerConnector - Creating client response for  POST "/api/v1/categories"
		08:50:01.114 [parallel-1] DEBUG org.springframework.web.reactive.function.client.ExchangeFunctions - [77c7ed8e] [7f4974ab] Response 500 INTERNAL_SERVER_ERROR
		08:50:01.129 [main] ERROR org.springframework.test.web.reactive.server.ExchangeResult - Request details for assertion failure:

		> POST /api/v1/categories
		> WebTestClient-Request-Id: [1]
		> Content-Type: [application/json]
		> Content-Length: [25]

		{"id":null,"name":"Cat1"}

		< 500 INTERNAL_SERVER_ERROR Internal Server Error
		<

		0 bytes of content (unknown content-type).

		java.lang.AssertionError: Status expected:<201 CREATED> but was:<500 INTERNAL_SERVER_ERROR>
		Expected :201 CREATED
		Actual   :500 INTERNAL_SERVER_ERROR

	SOLUTION:
		In the Controller forgot to add @RequestBody before the method parameter to tell Spring to bind the request body to the publisher parameter

		    @PostMapping
			@ResponseStatus(HttpStatus.CREATED)                                           // Make sure to return a 201 HTTP STATUS for object creations
			public Mono<Void> create(@RequestBody Publisher<Category> categoryStream) {  // called categoryStream as it can be a stream of one or more objects: Publisher is part of Reactive Streams API. Mono and Flux are implementations of a Publisher, so this method will be able to take in both.
				return categoryRepository.saveAll(categoryStream).then();   // .then() makes sure to return a Mono<Void>
			}

	So Spring didn't know what to do with it.